### ISSUE TITLE
How To Setup a Central Logging?

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-cloud#16]
One nice feature for the Imixs-Cloud would be a centralized logging.
I tried it with [Filebeat](https://www.elastic.co/products/beats/filebeat), [Elasticsearch](https://www.elastic.co/products/elasticsearch) and [Kibana](https://www.elastic.co/products/kibana) but did not succeed. So my question is if anybody can help me here.

The architecture should be quite simple:

    FileBeat            Elasticseach      Kibana
 
     worker1 ----->|
                   |
     worker3 ----->|---> Manager ----->  Manager
                   |
     worker3 ----->|

I created already a docker-compose.yml file to start up the stack. But this did not work. 

The current questions are:

 * How can I test if the filebeat worker nodes are working?
 * How can I test if the log information from a filebeat worker node is ingested by elasticsearch?
 * What are the steps to setup kibana to show the log information?

**Notes:** The concept should be quite simple for that reason [logstash](https://www.elastic.co/products/logstash) is not part of the stack!

So fare, my docker-compse.yml file looks like this:

```
version: '3.3'


networks:
  frontend:
    external:
      name: imixs-proxy-net 
  backend: 
  

services:


  ################################################################
  # elasticsearch
  #  - runs on manager node
  ################################################################
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      
    volumes:
      - elk-data:/usr/share/elasticsearch/data
    deploy:
      placement:
        constraints:
         # Hostname of the manager node!
         - node.hostname == manager-001
    networks:
      - backend




        
  ################################################################
  # filebeat
  #  - runs on manager node
  ################################################################      
  filebeat:
    image: docker.elastic.co/beats/filebeat:6.6.1
    command: setup -E setup.kibana.host=kibana:5601 -E output.elasticsearch.hosts=["elasticsearch:9200"] 
    depends_on:
      - elasticsearch
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker          
    networks:
      - backend


  ################################################################
  # Kibana
  #  - runs on manager node
  ################################################################      
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    depends_on:
      - elasticsearch

    deploy:
      labels:
        #traefik.port: "5601"
        #traefik.frontend.rule: "Host:logging.mycloud.com"
        #traefik.docker.network: "imixs-proxy-net" 
      replicas: 1
      placement:
        constraints:
         # Hostname of the manager node!
         - node.hostname == manager-001

    networks:
      - frontend
      - backend


volumes:
  elk-data:
```
