### ISSUE TITLE
Traefik web ui issue

### ISSUE THREAD

**Issue by ikit** [imixs/imixs-cloud#19]
Hi,

 I'm trying to setup imixs-cloud, and I would like to enable the web UI for traefik.
But I always got an 404 not found error. Note that traefik seems to work, I follow the tutorial and make the "routing" test whith the service whoiam and it works, the trafic label have been take in account... the problem is to enable the web UI.

I see on the [official website of traefik](https://docs.traefik.io/v1.7/configuration/web/) that the config file you are using in imixs-cloud is a little bit obsolete
`[web]` have been replaced by `[api]`... So I did as it was said in the doc, but I'm always facing the same issue...

I don't know how to debug my problem... maybe it's due to a missconfig with swarm or docker, traefik... maybe it's a bug of the trafic docker image...

:'( 

below my traefik config file
```
################################################################
# Global configuration
################################################################
# Enable debug mode
debug = true

# Log level
# "ERROR" or "DEBUG"
logLevel = "DEBUG"

# Entrypoints to be used by frontends that do not specify any entrypoint.
# Each frontend can specify its own entrypoints.
defaultEntryPoints = ["http"]

# Entrypoints definition
[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.traefik]
    address = ":8080"
#    [entryPoints.traefik.auth.basic]
#      users = ["test:test"]
    
# Traefik logs
# Enabled by default and log to stdout
# [traefikLog]

# Sets the filepath for the traefik log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
# filePath = "log/traefik.log"

# Format is either "json" or "common".
# format = "common"

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
# [accessLog]

# Sets the file path for the access log. If not specified, stdout will be used.
# Intermediate directories are created if necessary.
# filePath = "/path/to/log/log.txt"

# Format is either "json" or "common".
# format = "common"

################################################################
# Web configuration backend
################################################################
[api]
  # Name of the related entry point
  entryPoint = "traefik"

  # Enable Dashboard
  dashboard = true

  # Enable debug mode.
  # This will install HTTP handlers to expose Go expvars under /debug/vars and
  # pprof profiling data under /debug/pprof/.
  # Additionally, the log level will be set to DEBUG.
  debug = true


# To enable basic auth generate user credentials with htpasswd
[web.auth.basic]
users = ["test:test"]

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]
domain = "****"
watch = true
exposedbydefault = true
swarmmode = true

# Docker server endpoint. Can be a tcp or a unix socket endpoint.
#
# Required
# Default: "unix:///var/run/docker.sock"
#
# endpoint = "tcp://127.0.0.1:2377"

################################################################
# HTTPS - ACME
################################################################
#[acme]
#email = "***"
#storage = "/etc/traefik/acme/acme.json"
#entryPoint = "https"
#OnHostRule = true
#[acme.httpChallenge]
#  entryPoint = "http"
```

and my docker-compose file
```
version: '3.2'

services:
  app:
    image: traefik:v1.7.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/management/traefik/traefik.toml:/etc/traefik/traefik.toml
      - $PWD/management/traefik/acme:/etc/traefik/acme
    ports:
      - 80:80
      - 443:443
      - 8100:8080
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
     
networks:
   default:
    external:
      name:  imixs-proxy-net
```
