### ISSUE TITLE
Monitoring configuration

### ISSUE THREAD

**Issue by ikit** [imixs/imixs-cloud#20]
Hi,

I have a problem with the prometheus configuration.
In grafana, all seems to work, but monitoring data are not collected by prometheus
![](https://snipboard.io/PWZkyF.jpg)

It seems that node-exporter are not well configured...
![](https://snipboard.io/2WVHpu.jpg)

First the only things I change in prometheus/docker-compose files is to change "*-001" to "*-absg0"
But I noticed in portainer that container are all prefixed by `monitoring_` so I apply also this prefix in my config files, but the result is the same

below my configs files
prometheus.yml
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'codelab-monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
      
  - job_name: 'node-exporter'
    static_configs:
      # the targets listed here must match the service names from the docker-compose file
      - targets: ['monitoring_manager-absg0:9100','monitoring_worker-absg0:9100']

      
  - job_name: 'cadvisor'
    static_configs:
      # the targets listed here must match the service names from the docker-compose file
      - targets: ['monitoring_docker-manager-absg0:8080','monitoring_docker-worker-absg0:8080']
```

and docker-compose
```
version: '3.2'

networks:
  frontend:
    external:
      name: imixs-proxy-net 
  backend: 
  

services:

  ################################################################
  # Prometheus 
  #  - runs on manager node
  ################################################################
  prometheus:
    image: prom/prometheus
    volumes:
      - $PWD/management/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      #labels:
        #traefik.port: "9090"
        #traefik.frontend.rule: "Host:prometheus.myhost.com"
        #traefik.frontend.auth.basic.usersFile: /path/.htpasswd   
        #traefik.frontend.auth.basic.users: "admin:$$axxxxxxxxxxxxxxxxxxxxxxxxx"
        #traefik.docker.network: "imixs-proxy-net" 
      placement:
        constraints:
          - node.role == manager
    networks:
      - frontend
      - backend     


  ################################################################
  # The promethes node-exporter 
  # For each node a separte service need to be added 
  ################################################################
  # START NODE-EXPORTERS.....
  manager-absg0:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      placement:
        constraints:
         # Hostname of the manager node!
         - node.hostname == manager-absg0
    networks:
      - backend

  worker-absg0:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    deploy:
      placement:
        constraints:
         # Hostname of the first woker node!
         - node.hostname == worker-absg0
    networks:
      - backend
  ################################################################
  # END NODE-EXPORTERS.....
  ################################################################
      
      



  ################################################################
  # cAdvisor
  #   - runs on every node
  ################################################################
  # START CADVISORS.....
  docker-manager-absg0:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
         # Hostname of the first manager node!
          - node.hostname == manager-absg0
    networks:
      - backend

  docker-worker-absg0:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      placement:
        constraints:
         # Hostname of the first woker node!
          - node.hostname == worker-absg0
    networks:
      - backend

  ################################################################
  # END CADVISORS.....
  ################################################################
...
```

and the log that I got in all my node-exporter container : 
```
Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: task ja4iei39uikykuej5gl7cxigv has not been scheduled
```

Do you have an idea of what could be the problem ?

**Comment by rsoika** [comment]
I think your prometheus.yml file lists the wrong node names.

In your docker-compose file you define a prom/node-exporter for each host you whant to monitor (it collects the hardware metrics).
And there you give the service a name. e.g.:

```
 ....
 manager-absg0:
    image: prom/node-exporter
 ....
```


This service name is the one you need for the prometeus job 'node-exporter' in your prometeus.yml file
 e.g: 

```
....
job_name: 'node-exporter'
    static_configs:
      - targets: ['manager-absg0:9100',.....]
```


In your docker compose file you also define a cadvisor for each docker node (this one collectes the docker metrics):


```
.....
  docker-manager-absg0:
    image: google/cadvisor:latest
....
```


This service name is the one you need for the prometeus job 'cadvisor' in your prometeus.yml file 
 e.g: 

```
...
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['docker-manager-absg0',.....]
```


Before playing around with grafana, you can first check the prometheus ui running on port 9090. So you can verify if prometheus collects the data as expected. Grafana is just a nicer UI.
