### ISSUE TITLE
longhorn - fix deprecated csi driver name

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-cloud#32]
replace deprecated name  in 011-persistencevolume example

    io.rancher.longhorn 

into

    driver.longhorn.io

```
  csi:
    driver: io.rancher.longhorn 
    fsType: ext4
    volumeHandle: traefik-data
```
