### ISSUE TITLE
Auth system

### ISSUE THREAD

**Issue by letsbuildfoze** [imixs/imixs-cloud#38]
Hello,
Thanks for all your help.

I got another question.
For the auth system ( longhorn and traefik).
I try to change the password and put a only users.

Here my data custom block file:
data:
  username: YWRtaW4=
  password: xxxxxxxxxxxxxxxxxxxxxx

I try to change the 020 deploy of traefik to add the custom lines. 
But its not running i got the error on dashboard traefik "Cannot find the auth middleware".

**Comment by rsoika** [comment]
your ingress should look something like this:

```
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
spec:
  routes:
  - match: Host(`traefik.foo.om`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares: 
    - name: basic-auth
```


And first make sure the middleware is ins activated - you can do this by using the trafik dashboard.
