### ISSUE TITLE
Longhorn Volumeattachments error

### ISSUE THREAD

**Issue by ankanheesun** [imixs/imixs-cloud#40]
Dear, 
First of all, I would like to said that your git of lightweight k8s environment is awesome !!! I learned a lot from you and I want to say thank you for that. 
Besides, I am facing errors related to connect my PVC created by Longhorn storage class to my deployment. 
My deployment looks like:
> ...
        volumeMounts:
        - name: webroot
          mountPath: /var/www/html
      volumes:
      - name: webroot
        persistentVolumeClaim:
          claimName: minhdq-vn-data

whereas my PVC looks is very simple:
> apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minhdq-vn-data
  namespace: minhdq-vn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi

and here are logs I got from my Pod

> MountVolume.WaitForAttach failed for volume "pvc-XXX" : volume pvc-XXX has GET error for volume attachment csi-YYY: volumeattachments.storage.k8s.io "csi-YYY" is forbidden: User "system:node:master-k8s.local" cannot get resource "volumeattachments" in API group "storage.k8s.io" at the cluster scope: no relationship found between node "master-k8s.local" and this object

Could you please let me know how to bypass it? I already installed successfully all others components of k8s such as traefik, harbor, longhorn and monitoring exactly what you introduced.

Best,

**Comment by rsoika** [comment]
Its hard to say what is going wrong. Below is an example of a PostgreSQL Deployment in the namespace 'some-demo'. 
You can give it a try if this works for you. 

btw.: is the Longhorn UI working? You can monitor you longhorn instance with the Web UI and you should see event log entries if something is missing.


```
###################################################
# Deployment PostgreSQL
###################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: some-demo
  labels: 
    app: db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: test
        - name: POSTGRES_PASSWORD
          value: abc
        - name: POSTGRES_USER
          value: testuser
        image: postgres:9.6.1
        name: db

        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 30
          periodSeconds: 10

        ports:
          - containerPort: 5432        
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: dbdata
          subPath: postgres
      restartPolicy: Always
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata

---
###################################################
# Persistence Volume Claim
###################################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
  namespace: some-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
```
