### ISSUE TITLE
Documentation: longhorn UI 002-ingress.yaml??

### ISSUE THREAD

**Issue by koo9** [imixs/imixs-cloud#56]
it seems like the file content of 002-ingress.yaml in the longhorn folder is different than that in the doc here. https://imixs.github.io/imixs-cloud/doc/LONGHORN.html

the original 002-ingress.yaml is to create kind: ingress but the doc indicate that its creating kind: IngressRoute. 

which is correct?

**Comment by rsoika** [comment]
Thanks for the hint. 'ingress' is the correct one. I have updated the documentation.

**Comment by koo9** [comment]
When tried creating test app whoami, it looks like only IngressRoute works for Traefik.  003-ingress.yaml does not work. it won't add the route to traefik where IngressRoute does.

**Comment by rsoika** [comment]
You are mixing things here. 
In Kubernetes an "Ingress" is the official object to publish a service.
If you have a service defined you can add an ingress definition like this:

```
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: my-tls
  namespace: my-namespace
spec:
  rules:
  - host: myapp.foo.com
    http:
      paths:
      - path: /
        backend:
          serviceName: myservcie
          servicePort: 8080
```

Traefik is the reverse proxy managing the routing. If you do not have Traefik you need to install some other service (e.g. ngix)

Traefik itself has a Web UI. But this web UI must be configured via "IngressRoute". This is a traefik specific object and not a kubernetes standard!

    apiVersion: traefik.containo.us/v1alpha1
    kind: IngressRoute
    ...........


I think the IngressRoute is the only object that will do the trick to access the trafic-ui via web browser. This is why I use a different setup here.

For all other services you should use the core 'Ingress' object. If this does not work, than you can open the Traefik UI and see what is going wrong. Also it may be helpful to check the logfiles from your traefik service.

So first try to get the whoami example working. This is a kind of smoke-test for your cluster.

Longhorn is the next stage.....
