### ISSUE TITLE
How to persist data in the swarm....

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-cloud#8]
This is an open question. 
When we run databases (e.g. postgresql) we can not be where in the swarm the service will be provisioned and then how the volume gets mounted/bound for each replica.
In a first solution we can work with constraints provided by docker

```
deploy:
  placement:
    constraints:
      - node.hostname == node_hostname
```

But this will not support the idea of scaling containers over different bare metal servers. 
To support this scenario some other solutions are needded.

An interesting new project is:
https://infinit.sh/docker
https://github.com/infinit/infinit
